image: guideinvestimentos/ruby_freetds:2.5.0

pipelines:
  default:
    - step: &default_pipeline
        caches:
          - bundler
        script:
          - git archive --remote=git@bitbucket.org:guideinvestimentos/rails_defaults.git HEAD .rubocop.yml | tar -x
          - bundle install --path vendor/bundle
          - gem install rubocop
          - rubocop
        artifacts:
          - coverage/**
          - vendor/bundle/**
  branches:
    devel:
      - step: *default_pipeline
      - step:
          name: sonar
          image: newtmitch/sonar-scanner
          script:
            - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
            - |
              sonar-scanner \
              -D sonar.host.url=$SONAR_HOST_URL \
              -D sonar.login=$SONAR_LOGIN \
              -D sonar.projectBaseDir=$BITBUCKET_CLONE_DIR \
              -D sonar.projectName=$BITBUCKET_REPO_SLUG-dev \
              -D sonar.projectKey=$BITBUCKET_REPO_SLUG-dev
      - step:
          script:
            - |
              docker build \
              -t guideinvestimentos/$BITBUCKET_REPO_SLUG:development \
              . \
              --build-arg INSTALL_PATH=/$COMPOSE_PROJECT_NAME
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker push guideinvestimentos/$BITBUCKET_REPO_SLUG:development
    '{hotfix/*,release/*}':
      - step: *default_pipeline
      - step: &sonar
          name: sonar
          image: newtmitch/sonar-scanner
          script:
            - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
            - |
              sonar-scanner \
              -D sonar.host.url=$SONAR_HOST_URL \
              -D sonar.login=$SONAR_LOGIN \
              -D sonar.projectBaseDir=$BITBUCKET_CLONE_DIR \
              -D sonar.projectName=$BITBUCKET_REPO_SLUG \
              -D sonar.projectKey=$BITBUCKET_REPO_SLUG
      - step:
          script:
            - VERSION=$(cat .version)
            - |
              docker build \
              -t guideinvestimentos/$BITBUCKET_REPO_SLUG:$VERSION-rc \
              . \
              --build-arg INSTALL_PATH=/$COMPOSE_PROJECT_NAME
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker push guideinvestimentos/$BITBUCKET_REPO_SLUG:$VERSION-rc
    master:
      - step:
          script:
            - VERSION=$(cat .version)
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker pull guideinvestimentos/$BITBUCKET_REPO_SLUG:$VERSION-rc
            - |
              docker tag \
              guideinvestimentos/$BITBUCKET_REPO_SLUG:$VERSION-rc \
              guideinvestimentos/$BITBUCKET_REPO_SLUG:$VERSION
            - |
              docker tag \
              guideinvestimentos/$BITBUCKET_REPO_SLUG:$VERSION-rc \
              guideinvestimentos/$BITBUCKET_REPO_SLUG:latest
            - docker push guideinvestimentos/$BITBUCKET_REPO_SLUG:$VERSION
            - docker push guideinvestimentos/$BITBUCKET_REPO_SLUG:latest
definitions:
  caches:
    bundler: vendor/bundle
options:
  docker: true
