version: '3.1'
services:
  db:
    image: nouchka/sqlite3
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:5
    volumes:
      - "./:/app"
    ports:
      - '8080:8080'
    command: ruby web/server.rb -o 0.0.0.0 -p 8080
    env_file:
      - '.env'
  robot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:5
    stdin_open: true
    tty: true
    volumes:
      - "./:/app"
    command: cucumber
    env_file:
      - '.env'
