version: '2'
services:
  fifa_autotrader:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_PATH: "/${COMPOSE_PROJECT_NAME}"
    stdin_open: true
    tty: true
    environment:
      DEBUG: 'true'
    volumes:
      - "./:/${COMPOSE_PROJECT_NAME}"
    command:
      - /bin/sh
      - -c
      - |
        bundle exec cucumber
    env_file:
      - '.env'
