version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - "./:/app"
    ports:
      - '8080:8080'
    command: rackup -o 0.0.0.0 -p 8080
    env_file:
      - '.env'
  robot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - "./:/app"
    command: cucumber
    env_file:
      - '.env'
