source 'https://rubygems.org'

gem 'pry'
gem 'pry-byebug'
gem 'capybara'
gem 'json'
gem 'rspec'
gem 'cucumber'
gem 'selenium-webdriver'
gem 'whenever'
gem 'lograge'
gem 'logstash-logger'
gem 'chronic_duration'
gem 'awesome_print'
gem 'google-apis-gmail_v1'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'haml'
