---
General:
  FIFA_PLATFORM: pc
  EA_TAX: 0.05
Login:
  ORIGIN_EMAIL: default@email.com
  ORIGIN_PASSWORD: XXX
Market:
  MAX_STOCK: 3
  MAX_TIME_LEFT: 720
  MAX_PLAYER_BIDS: 4
  MARKET_INTERVAL: 600
Trade Optimizer:
  MIN_BID: 850
  MIN_SELL: 1600
  BID_RATIO: 0.7
  SELL_RATIO: 1.1
  AUTO_OPTIMIZE_VALUES: 1
