---
FIFA_PLATFORM: pc
EA_TAX: 0.05
ORIGIN_EMAIL: default@email.com
ORIGIN_PASSWORD: XXX
MAX_STOCK: 3
MAX_TIME_LEFT: 720
MAX_PLAYER_BIDS: 4
MARKET_INTERVAL: 600
MIN_BID: 850
MIN_SELL: 1600
AUTO_OPTIMIZE_VALUES: 1
